/** @repo-prism/core — public SDK façade (only supported integration surface). */

export { Prism, type PrismClient, type PrismClientOptions } from "./prism.js";
export type { ChangedPaths } from "./git/changed-paths.js";
export type { PrismGitignoreStatus } from "./git/prism-gitignore.js";
export { loadPrismConfig, loadPrismConfigSync } from "./prism-config-load.js";
export { writePrismConfig } from "./prism-config-write.js";
export {
  createWorkspace,
  type FeatureGraphView,
  type FindRouteQuery,
  type GetDomainReportOptions,
  type GetRepositoryMapOptions,
  type GetOverviewModelOptions,
  type GetStackProfileOptions,
  type GetUtilityOverlayOptions,
  type IndexFreshness,
  type KnowledgeGraphView,
  type NotifyWatchPathsInput,
  type PrismWorkspace,
  type ReviewChangesInput,
  type RunWorkspaceTestsOptions,
  type SaveBookmarkInput,
  type StartWatchOptions,
  type WorkspacePackageInfo,
  type WorkspaceStatus,
  type WorkspaceTestList,
} from "./workspace.js";
export type { RouteEndpoint } from "@repo-prism/navigation";
export type {
  DependencyGraphOptions,
  FindReferencesQuery,
  FindReferencesResult,
  FindSymbolQuery,
  ReferenceHit,
  SearchSymbolsQuery,
  StartUtilityJobInput,
  SymbolHit,
} from "@repo-prism/intelligence";
export {
  UTILITY_JOB_BUNDLE_STATS,
  UTILITY_JOB_ECHO,
  UTILITY_JOB_LIGHTHOUSE,
  UTILITY_JOB_REMOTE_PROBE_STUB,
} from "@repo-prism/intelligence";
export type {
  BackendReport,
  BlastRadiusReport,
  BreakingChangeHint,
  BundleAnalyzeCapability,
  BundleWeightReport,
  ChangeOrigin,
  ChangeReviewItem,
  ChangeReviewReport,
  CodeExplorerReport,
  CodeExplorerTarget,
  ConsentRecord,
  CwvReport,
  BackendDomainReport,
  DataMlAiDomainReport,
  DesktopDomainReport,
  DevopsDomainReport,
  DomainReport,
  DnaReport,
  FrontendDomainReport,
  MobileDomainReport,
  EngineeringHealthReport,
  ExplainAreaSummary,
  FeatureInfo,
  GitActivity,
  DependencyGraphDto,
  GraphSnapshotDto,
  HealthHistoryBackfillStatus,
  HealthHistoryReport,
  HealthScore,
  ImpactEditSite,
  IndexSnapshot,
  IndexSummary,
  IngestArtifact,
  IngestArtifactMeta,
  IntelligenceConsistency,
  IntelligenceReport,
  KnowledgeGraphStats,
  Landmark,
  MapBookmark,
  MapZoomLevel,
  NavigationRoute,
  NavigationRouteResult,
  PersonaPresets,
  PrismError,
  RegionMoversReport,
  RenameImpactReport,
  RepositoryMap,
  Result,
  SafeDeleteReport,
  StackPackageProfile,
  StackProfile,
  TestImpactReport,
  TestingReport,
  SecurityReport,
  UtilityJob,
  UtilityOverlayKind,
  UtilityOverlayKindInfo,
  UtilityOverlayReport,
} from "@repo-prism/shared";
export { PrismErrorCode, err, ok, prismError } from "@repo-prism/shared";
export { STUB_CAPABILITIES, type PrismCapabilities } from "./capabilities.js";
export type {
  AnalyzerPort,
  GraphEnginePort,
  IndexerPort,
  LanguagePluginInfo,
  PrismEnginePorts,
  StackDetectorInfo,
  StackPort,
} from "./ports.js";
export { PRISM_API_LEVEL, PRISM_CORE_VERSION } from "./version.js";
export {
  stageDevopsRemote,
  type StageDevopsRemoteInput,
  type StageDevopsRemoteResult,
  type StagedWorkflowSummary,
} from "./stage-devops-remote.js";
export {
  dispatchGithubWorkflow,
  fetchGithubAuthenticatedLogin,
  fetchGithubRepo,
  fetchGithubWorkflowRuns,
  fetchGithubWorkflows,
  testGithubRepoConnection,
  type DispatchGithubWorkflowInput,
  type DispatchWorkflowInput,
  type DispatchWorkflowKind,
  type GithubCiConfig,
  type GithubCiNetworkInput,
  type GithubRepoInfo,
  type GithubWorkflowRun,
  type GithubWorkflowSummary,
} from "./github-ci.js";
export {
  fetchPagespeedMetrics,
  type FetchPagespeedMetricsInput,
} from "./pagespeed.js";
export {
  listLocalWorkspaceTests,
  runLocalWorkspaceTests,
  type LocalRunTestsOptions,
  type LocalRunTestsResult,
  type LocalTestListResult,
} from "./testing/local-runners.js";
