/** Node-kind → display label + accent (falls back to title-case + slate). */
export const KIND_META: Record<string, { label: string; color: string }> = {
  handler: { label: "Handler", color: "#3B82F6" },
  "route-table": { label: "Routes", color: "#00C2C2" },
  openapi: { label: "OpenAPI", color: "#10B981" },
  "grpc-proto": { label: "gRPC", color: "#A855F7" },
  screen: { label: "Screen", color: "#6C63FF" },
  navigator: { label: "Navigator", color: "#00C2C2" },
  hook: { label: "Hook", color: "#F59E0B" },
  service: { label: "Service", color: "#3B82F6" },
  module: { label: "Module", color: "#A855F7" },
  route: { label: "Route", color: "#3B82F6" },
  main: { label: "Main", color: "#F59E0B" },
  preload: { label: "Preload", color: "#00C2C2" },
  renderer: { label: "Renderer", color: "#6C63FF" },
  ipc: { label: "IPC", color: "#F43F5E" },
  "tauri-config": { label: "Tauri", color: "#FFC131" },
  test: { label: "Test", color: "#10B981" },
  "test-package": { label: "Test Pkg", color: "#10B981" },
  terraform: { label: "Terraform", color: "#7B42BC" },
  helm: { label: "Helm", color: "#0F1689" },
  kubernetes: { label: "Kubernetes", color: "#326CE5" },
  container: { label: "Container", color: "#2496ED" },
  ci: { label: "Pipeline", color: "#00C2C2" },
  model: { label: "Models", color: "#3B82F6" },
  migration: { label: "Migrations", color: "#00C2C2" },
  sql: { label: "SQL", color: "#10B981" },
  client: { label: "DB Clients", color: "#A855F7" },
};
