/** @prism/shared — contracts, errors, IDs, paths, Zod DTOs */

export {
  err,
  isErr,
  isOk,
  mapResult,
  ok,
  unwrap,
  type Result,
} from "./result.js";

export {
  PrismErrorCode,
  isPrismError,
  prismError,
  type PrismError,
  type PrismErrorCode as PrismErrorCodeType,
} from "./errors.js";

export {
  asEdgeId,
  asFeatureId,
  asFileId,
  asNodeId,
  asRepoId,
  asSymbolId,
  unsafeEdgeId,
  unsafeFeatureId,
  unsafeFileId,
  unsafeNodeId,
  unsafeRepoId,
  unsafeSymbolId,
  type EdgeId,
  type FeatureId,
  type FileId,
  type NodeId,
  type RepoId,
  type SymbolId,
} from "./ids.js";

export {
  isRepoRelativePath,
  joinRepoPath,
  normalizeRepoPath,
  type RepoRelativePath,
} from "./paths.js";

export {
  BlastRadiusItemSchema,
  BlastRadiusReportSchema,
  DnaReportSchema,
  FeatureInfoSchema,
  FileInventoryEntrySchema,
  FileInventorySchema,
  FileInventoryStatusSchema,
  GraphEdgeDtoSchema,
  GraphLayoutPositionSchema,
  GraphLayoutSchema,
  GraphNodeDtoSchema,
  GraphSnapshotDtoSchema,
  HealthScoreSchema,
  IndexCacheStatsSchema,
  IndexFileStatsSchema,
  IndexProgressEventSchema,
  IndexProgressPhaseSchema,
  IndexSnapshotSchema,
  IndexSummarySchema,
  IndexedExportSchema,
  IndexedFileSchema,
  IndexedFileStatusSchema,
  IndexedImportSchema,
  IndexedReferenceSchema,
  IndexedSymbolSchema,
  ConsentRecordSchema,
  CwvAttributionSchema,
  CwvMetricIdSchema,
  CwvMetricSchema,
  CwvRatingSchema,
  CwvReportSchema,
  CwvRollupBucketSchema,
  IngestArtifactKindSchema,
  IngestArtifactMetaSchema,
  IngestArtifactSchema,
  IntelligenceConsistencyIssueSchema,
  IntelligenceConsistencySchema,
  IntelligenceReportSchema,
  JsonValueSchema,
  KnowledgeGraphStatsSchema,
  ParseDiagnosticDtoSchema,
  PersonaPresetsSchema,
  PrismCapabilitiesDtoSchema,
  PrismErrorSchema,
  RepoRelativePathSchema,
  StackPackageProfileSchema,
  StackProfileCoreSchema,
  StackProfileSchema,
  StackSignalSchema,
  UtilityJobKindSchema,
  UtilityJobProgressSchema,
  UtilityJobSchema,
  UtilityJobStatusSchema,
  UtilityMapLayerSchema,
  UtilityOverlayFindingSchema,
  UtilityOverlayKindInfoSchema,
  UtilityOverlayKindSchema,
  UtilityOverlayReportSchema,
  parseDto,
  type BlastRadiusReport,
  type ConsentRecord,
  type CwvAttribution,
  type CwvMetric,
  type CwvMetricId,
  type CwvRating,
  type CwvReport,
  type CwvRollupBucket,
  type DnaReport,
  type FeatureInfo,
  type FileInventory,
  type FileInventoryEntry,
  type FileInventoryStatus,
  type GraphEdgeDto,
  type GraphLayout,
  type GraphLayoutPosition,
  type GraphNodeDto,
  type GraphSnapshotDto,
  type HealthScore,
  type IndexCacheStats,
  type IndexProgressEvent,
  type IndexProgressPhase,
  type IndexSnapshot,
  type IndexSummary,
  type IndexedExport,
  type IndexedFile,
  type IndexedFileStatus,
  type IndexedImport,
  type IndexedReference,
  type IndexedSymbol,
  type IngestArtifact,
  type IngestArtifactKind,
  type IngestArtifactMeta,
  type IntelligenceConsistency,
  type IntelligenceConsistencyIssue,
  type IntelligenceReport,
  type JsonValue,
  type KnowledgeGraphStats,
  type ParseDiagnosticDto,
  type PersonaPresets,
  type PrismCapabilitiesDto,
  type PrismErrorDto,
  type StackPackageProfile,
  type StackProfile,
  type StackProfileCore,
  type StackSignal,
  type UtilityJob,
  type UtilityJobKind,
  type UtilityJobProgress,
  type UtilityJobStatus,
  type UtilityMapLayer,
  type UtilityOverlayFinding,
  type UtilityOverlayKind,
  type UtilityOverlayKindInfo,
  type UtilityOverlayReport,
} from "./schemas.js";

export {
  DeveloperPersona,
  StackDomain,
  type DeveloperPersonaId,
  type StackDomainId,
  type WellKnownDeveloperPersona,
  type WellKnownStackDomain,
} from "./stack.js";
