/** @repo-prism/shared — contracts, errors, IDs, paths, Zod DTOs */

export {
  err,
  isErr,
  isOk,
  mapResult,
  ok,
  unwrap,
  type Result,
} from "./result.js";

export {
  PrismErrorCode,
  isPrismError,
  prismError,
  type PrismError,
  type PrismErrorCode as PrismErrorCodeType,
} from "./errors.js";

export { isTestPath, isTypeDeclarationPath } from "./test-paths.js";

export {
  CONSENT_PURPOSES,
  CONSENT_PURPOSE_IDS,
  ConsentPurposeIdSchema,
  consentPurpose,
  consentRequiredMessage,
  isConsentPurposeId,
  type ConsentPurpose,
  type ConsentPurposeGroup,
  type ConsentPurposeId,
  type ConsentState,
} from "./consent-purposes.js";

export {
  RISK_BANDS,
  RISK_BAND_IDS,
  RISK_BAND_MIN,
  RiskBandSchema,
  riskBandDescriptor,
  riskToBand,
  type RiskBand,
  type RiskBandDescriptor,
} from "./risk-bands.js";

export {
  DEFAULT_PROVENANCE,
  ProvenancedValueSchema,
  SIGNAL_PROVENANCE,
  SignalProvenanceSchema,
  combineProvenance,
  estimated,
  hasValue,
  heuristic,
  inferred,
  measured,
  unavailable,
  valueOr,
  type ProvenancedValue,
  type SignalProvenance,
} from "./provenance.js";

export {
  asEdgeId,
  asFeatureId,
  asFileId,
  asNodeId,
  asRepoId,
  asSymbolId,
  unsafeEdgeId,
  unsafeFeatureId,
  unsafeFileId,
  unsafeNodeId,
  unsafeRepoId,
  unsafeSymbolId,
  type EdgeId,
  type FeatureId,
  type FileId,
  type NodeId,
  type RepoId,
  type SymbolId,
} from "./ids.js";

export {
  isRepoRelativePath,
  joinRepoPath,
  normalizeRepoPath,
  type RepoRelativePath,
} from "./paths.js";

export {
  classifyToolingRoot,
  isRepoCriticalPath,
  type ToolingCriticality,
} from "./tooling-criticality.js";

export {
  classifyFileRole,
  fileRoleLabel,
  fileRoleRiskFloor,
  type FileRole,
} from "./file-role.js";

export {
  PRISM_CONFIG_FILENAME,
  PRISM_CONFIG_RELATIVE_PATH,
  PrismConfigSchema,
  maxFileSizeOptionToBytes,
  mergeIndexLimits,
  parsePrismConfig,
  type PrismConfig,
} from "./prism-config.js";

export {
  bucketActivity,
  couplingBand,
  couplingDensity,
  couplingDensityPct,
  couplingFor,
  deriveMostConnected,
  deriveRegions,
  floorToUtcDay,
  parseDayMs,
  presetBounds,
  type DeriveRegionsResult,
} from "./overview-model.js";

export {
  backendHandlerNodes,
  buildBackendCoverage,
  buildDesktopBoundaryLinks,
  buildDesktopIpcChannels,
  buildDesktopTiles,
  buildDevopsFindings,
  buildDevopsTiles,
  buildDomainStackSnapshot,
  buildFrontendComponentBreakdown,
  buildFrontendRouteBreakdown,
  buildMobileNavLinks,
  buildMobileScreenCoverage,
  buildMobileTiles,
  buildOverlayLinks,
  countDataLayerByKind,
  countOverlayKinds,
  desktopProcessNodes,
  fileStem,
  inboundDepCounts,
  kindCountOf,
  lookupInbound,
  mergeFrontendRoutes,
  normalizeDepKey,
  overlayNodePath,
  rankChurnHotspots,
  rankMostDepended,
  selectPrimaryCwv,
  summarizeBackendDomainReport,
  summarizeDataMlAiDomainReport,
  summarizeDesktopDomainReport,
  summarizeDevopsDomainReport,
  summarizeFrontendDomainReport,
  summarizeMobileDomainReport,
} from "./domain-report.js";

export {
  BlastRadiusItemSchema,
  BlastImpactCategorySchema,
  ImpactLaneSchema,
  ImpactConfidenceSchema,
  BlastLaneSummarySchema,
  FileRoleSchema,
  ForwardDependencyItemSchema,
  ScenarioChecklistSectionSchema,
  BlastRadiusReportSchema,
  BreakingChangeHintSchema,
  ChangeOriginSchema,
  ImpactEditSiteSchema,
  SafeDeleteReportSchema,
  RenameImpactReportSchema,
  TestImpactReportSchema,
  ChangeReviewItemSchema,
  ChangeReviewReportSchema,
  ExplainAreaSummarySchema,
  DnaReportSchema,
  RankedDomainSchema,
  FeatureInfoSchema,
  FileInventoryEntrySchema,
  FileInventorySchema,
  FileInventoryStatusSchema,
  DependencyGraphDtoSchema,
  GraphEdgeDtoSchema,
  GraphLayoutPositionSchema,
  GraphLayoutSchema,
  GraphNodeDtoSchema,
  GraphSnapshotDtoSchema,
  UnresolvedImportsSummarySchema,
  GitActivitySchema,
  GitAuthorRollupSchema,
  GitCommitRefSchema,
  GitContributorSchema,
  GitDayBucketSchema,
  GitFileSignalSchema,
  GitRecentFileSchema,
  GitRepoSummarySchema,
  GitSyncStatusSchema,
  OverviewActivitySchema,
  OverviewConnectedNodeSchema,
  OverviewCouplingBandSchema,
  OverviewCouplingSchema,
  OverviewModelSchema,
  OverviewRegionSchema,
  OverviewTotalsSchema,
  BackendCoverageSchema,
  BackendDataLayerCountsSchema,
  BackendDomainReportSchema,
  CwvPreferredSourceSchema,
  DataMlAiDomainReportSchema,
  DesktopDomainReportSchema,
  DesktopIpcChannelSchema,
  DesktopTilesSchema,
  DevopsDomainReportSchema,
  DevopsTilesSchema,
  DomainChurnRowSchema,
  DomainKindCountSchema,
  DomainOverlayLinkSchema,
  DomainRankedNodeSchema,
  DomainReportDomainSchema,
  DomainReportSchema,
  DomainStackSnapshotSchema,
  FrontendComponentBreakdownRowSchema,
  FrontendDomainCwvBundleSchema,
  FrontendDomainReportSchema,
  FrontendRouteBreakdownRowSchema,
  MobileDomainReportSchema,
  MobileScreenCoverageSchema,
  MobileTilesSchema,
  HealthFactorBreakdownItemSchema,
  HealthFactorSchema,
  HealthHistoryBackfillStatusSchema,
  HealthHistoryPointSchema,
  HealthHistoryReportSchema,
  HealthScoreSchema,
  RegionHealthPointSchema,
  RegionMoversReportSchema,
  LandmarkSchema,
  MapBookmarkSchema,
  MapBookmarkStoreSchema,
  MapClusterSchema,
  MapLayerDescriptorSchema,
  MAP_ZOOM_LEVELS,
  MapLayerIdSchema,
  MapSearchHitSchema,
  MapZoomLevelSchema,
  NavigationRouteResultSchema,
  NavigationRouteSchema,
  RepositoryMapSchema,
  IndexCacheStatsSchema,
  IndexFileStatsSchema,
  IndexProgressEventSchema,
  IndexProgressPhaseSchema,
  IndexSnapshotSchema,
  IndexSummarySchema,
  IndexedExportSchema,
  IndexedFileSchema,
  IndexedFileStatusSchema,
  IndexedImportSchema,
  IndexedReferenceSchema,
  IndexedSymbolSchema,
  BundleAnalyzeCapabilitySchema,
  BundleAnalyzePackageInfoSchema,
  BundleAnalyzeScriptInfoSchema,
  BundleAnalyzeStrategySchema,
  BundleBuildLabelSchema,
  BundleBundlerSchema,
  BundleBytesSchema,
  BundleChunkSchema,
  BundleHighlightSchema,
  BundleHighlightSeveritySchema,
  BundleLoadTypeSchema,
  BundleModuleSchema,
  BundlePackageRollupSchema,
  BundleWeightOverviewSchema,
  BundleWeightReportSchema,
  BundleWeightThresholdsSchema,
  ConsentRecordSchema,
  CwvAttributionSchema,
  CwvInsightSchema,
  CwvInsightSeveritySchema,
  CwvMetricIdSchema,
  CwvMetricSchema,
  CwvRatingSchema,
  CwvReportSchema,
  CwvRouteLabProgressDetailSchema,
  CwvRollupBucketSchema,
  IngestArtifactKindSchema,
  IngestArtifactMetaSchema,
  IngestArtifactSchema,
  IntelligenceConsistencyIssueSchema,
  IntelligenceConsistencySchema,
  IntelligenceReportSchema,
  JsonValueSchema,
  KnowledgeGraphStatsSchema,
  ParseDiagnosticDtoSchema,
  PersonaPresetsSchema,
  PrismCapabilitiesDtoSchema,
  PrismErrorSchema,
  RepoRelativePathSchema,
  StackPackageProfileSchema,
  StackProfileCoreSchema,
  StackProfileSchema,
  StackSignalSchema,
  UtilityJobKindSchema,
  UtilityJobProgressSchema,
  UtilityJobSchema,
  UtilityJobStatusSchema,
  UtilityMapLayerSchema,
  UtilityOverlayFindingSchema,
  UtilityOverlayKindInfoSchema,
  UtilityOverlayKindSchema,
  UtilityOverlayReportSchema,
  BackendAuthExposureSchema,
  BackendFrameworkSchema,
  BackendEndpointSchema,
  BackendDataLayerItemSchema,
  BackendEnvVarSchema,
  BackendIntegrationSchema,
  BackendBackgroundJobSchema,
  BackendReportSchema,
  TestingSuiteKindSchema,
  TestingSuiteSchema,
  TestingCoverageSchema,
  TestingTestStatusSchema,
  TestingTestResultSchema,
  TestingReportSchema,
  SecurityToolSchema,
  SecurityCheckStatusSchema,
  SecurityCheckSchema,
  SecurityReportSchema,
  EngineeringHealthMetricIdSchema,
  EngineeringHealthMetricSchema,
  EngineeringHotspotKindSchema,
  EngineeringHotspotSchema,
  EngineeringHealthReportSchema,
  CodeExplorerTargetSchema,
  CodeExplorerUsageSchema,
  CodeExplorerOwnerSchema,
  CodeExplorerOwnershipSchema,
  CodeExplorerRelatedItemSchema,
  CodeExplorerRelatedSchema,
  CodeExplorerSimilarItemSchema,
  CodeExplorerTimelineSchema,
  CodeExplorerReportSchema,
  parseDto,
  type BlastRadiusItem,
  type BlastImpactCategory,
  type ImpactLane,
  type ImpactConfidence,
  type BlastLaneSummary,
  type ForwardDependencyItem,
  type ScenarioChecklistSection,
  type BlastRadiusReport,
  type BreakingChangeHint,
  type ChangeOrigin,
  type ImpactEditSite,
  type SafeDeleteReport,
  type RenameImpactReport,
  type TestImpactReport,
  type ChangeReviewItem,
  type ChangeReviewReport,
  type ExplainAreaSummary,
  type BundleAnalyzeCapability,
  type BundleAnalyzePackageInfo,
  type BundleAnalyzeScriptInfo,
  type BundleAnalyzeStrategy,
  type BundleBuildLabel,
  type BundleBundler,
  type BundleBytes,
  type BundleChunk,
  type BundleHighlight,
  type BundleHighlightSeverity,
  type BundleLoadType,
  type BundleModule,
  type BundlePackageRollup,
  type BundleWeightOverview,
  type BundleWeightReport,
  type BundleWeightThresholds,
  type ConsentRecord,
  type CwvAttribution,
  type CwvInsight,
  type CwvInsightSeverity,
  type CwvMetric,
  type CwvMetricId,
  type CwvRating,
  type CwvReport,
  type CwvRouteLabProgressDetail,
  type CwvRollupBucket,
  type DnaReport,
  type RankedDomain,
  type FeatureInfo,
  type FileInventory,
  type FileInventoryEntry,
  type FileInventoryStatus,
  type GitActivity,
  type GitAuthorRollup,
  type GitCommitRef,
  type GitContributor,
  type GitDayBucket,
  type GitFileSignal,
  type GitRecentFile,
  type GitRepoSummary,
  type GitSyncStatus,
  type OverviewActivity,
  type OverviewConnectedNode,
  type OverviewCoupling,
  type OverviewCouplingBand,
  type OverviewModel,
  type OverviewRegion,
  type OverviewTotals,
  type BackendCoverage,
  type BackendDataLayerCounts,
  type BackendDomainReport,
  type CwvPreferredSource,
  type DataMlAiDomainReport,
  type DesktopDomainReport,
  type DesktopIpcChannel,
  type DesktopTiles,
  type DevopsDomainReport,
  type DevopsTiles,
  type DomainChurnRow,
  type DomainKindCount,
  type DomainOverlayLink,
  type DomainRankedNode,
  type DomainReport,
  type DomainReportDomain,
  type DomainStackSnapshot,
  type FrontendComponentBreakdownRow,
  type FrontendDomainCwvBundle,
  type FrontendDomainReport,
  type FrontendRouteBreakdownRow,
  type MobileDomainReport,
  type MobileScreenCoverage,
  type MobileTiles,
  type GraphEdgeDto,
  type GraphLayout,
  type GraphLayoutPosition,
  type DependencyGraphDto,
  type GraphNodeDto,
  type GraphSnapshotDto,
  type UnresolvedImportsSummary,
  type HealthFactor,
  type HealthFactorBreakdownItem,
  type HealthHistoryBackfillStatus,
  type HealthHistoryPoint,
  type HealthHistoryReport,
  type HealthScore,
  type RegionHealthPoint,
  type RegionMoversReport,
  type Landmark,
  type MapBookmark,
  type BackendAuthExposure,
  type BackendFramework,
  type BackendEndpoint,
  type BackendDataLayerItem,
  type BackendEnvVar,
  type BackendIntegration,
  type BackendBackgroundJob,
  type BackendReport,
  type TestingSuiteKind,
  type TestingSuite,
  type TestingCoverage,
  type TestingTestStatus,
  type TestingTestResult,
  type TestingReport,
  type SecurityTool,
  type SecurityCheckStatus,
  type SecurityCheck,
  type SecurityReport,
  type EngineeringHealthMetricId,
  type EngineeringHealthMetric,
  type EngineeringHotspotKind,
  type EngineeringHotspot,
  type EngineeringHealthReport,
  type CodeExplorerTarget,
  type CodeExplorerUsage,
  type CodeExplorerOwner,
  type CodeExplorerOwnership,
  type CodeExplorerRelatedItem,
  type CodeExplorerRelated,
  type CodeExplorerSimilarItem,
  type CodeExplorerTimeline,
  type CodeExplorerReport,
  type MapBookmarkStore,
  type MapCluster,
  type MapLayerDescriptor,
  type MapLayerId,
  type MapSearchHit,
  type MapZoomLevel,
  type NavigationRoute,
  type NavigationRouteResult,
  type RepositoryMap,
  type IndexCacheStats,
  type IndexProgressEvent,
  type IndexProgressPhase,
  type IndexSnapshot,
  type IndexSummary,
  type IndexedExport,
  type IndexedFile,
  type IndexedFileStatus,
  type IndexedImport,
  type IndexedReference,
  type IndexedSymbol,
  type IngestArtifact,
  type IngestArtifactKind,
  type IngestArtifactMeta,
  type IntelligenceConsistency,
  type IntelligenceConsistencyIssue,
  type IntelligenceReport,
  type JsonValue,
  type KnowledgeGraphStats,
  type ParseDiagnosticDto,
  type PersonaPresets,
  type PrismCapabilitiesDto,
  type PrismErrorDto,
  type StackPackageProfile,
  type StackProfile,
  type StackProfileCore,
  type StackSignal,
  type UtilityJob,
  type UtilityJobKind,
  type UtilityJobProgress,
  type UtilityJobStatus,
  type UtilityMapLayer,
  type UtilityOverlayFinding,
  type UtilityOverlayKind,
  type UtilityOverlayKindInfo,
  type UtilityOverlayReport,
} from "./schemas.js";

export {
  DeveloperPersona,
  StackDomain,
  type DeveloperPersonaId,
  type StackDomainId,
  type WellKnownDeveloperPersona,
  type WellKnownStackDomain,
} from "./stack.js";
