/** @prism/shared — contracts, errors, IDs, paths, Zod DTOs */

export {
  err,
  isErr,
  isOk,
  mapResult,
  ok,
  unwrap,
  type Result,
} from "./result.js";

export {
  PrismErrorCode,
  isPrismError,
  prismError,
  type PrismError,
  type PrismErrorCode as PrismErrorCodeType,
} from "./errors.js";

export {
  asEdgeId,
  asFeatureId,
  asFileId,
  asNodeId,
  asRepoId,
  asSymbolId,
  unsafeEdgeId,
  unsafeFeatureId,
  unsafeFileId,
  unsafeNodeId,
  unsafeRepoId,
  unsafeSymbolId,
  type EdgeId,
  type FeatureId,
  type FileId,
  type NodeId,
  type RepoId,
  type SymbolId,
} from "./ids.js";

export {
  isRepoRelativePath,
  joinRepoPath,
  normalizeRepoPath,
  type RepoRelativePath,
} from "./paths.js";

export {
  BlastRadiusItemSchema,
  BlastRadiusReportSchema,
  BreakingChangeHintSchema,
  ChangeOriginSchema,
  ImpactEditSiteSchema,
  SafeDeleteReportSchema,
  RenameImpactReportSchema,
  TestImpactReportSchema,
  DnaReportSchema,
  FeatureInfoSchema,
  FileInventoryEntrySchema,
  FileInventorySchema,
  FileInventoryStatusSchema,
  GraphEdgeDtoSchema,
  GraphLayoutPositionSchema,
  GraphLayoutSchema,
  GraphNodeDtoSchema,
  GraphSnapshotDtoSchema,
  GitActivitySchema,
  GitCommitRefSchema,
  GitContributorSchema,
  GitDayBucketSchema,
  GitFileSignalSchema,
  GitRecentFileSchema,
  GitRepoSummarySchema,
  GitSyncStatusSchema,
  HealthScoreSchema,
  LandmarkSchema,
  MapBookmarkSchema,
  MapBookmarkStoreSchema,
  MapClusterSchema,
  MapLayerDescriptorSchema,
  MapLayerIdSchema,
  MapSearchHitSchema,
  MapZoomLevelSchema,
  NavigationRouteResultSchema,
  NavigationRouteSchema,
  RepositoryMapSchema,
  IndexCacheStatsSchema,
  IndexFileStatsSchema,
  IndexProgressEventSchema,
  IndexProgressPhaseSchema,
  IndexSnapshotSchema,
  IndexSummarySchema,
  IndexedExportSchema,
  IndexedFileSchema,
  IndexedFileStatusSchema,
  IndexedImportSchema,
  IndexedReferenceSchema,
  IndexedSymbolSchema,
  ConsentRecordSchema,
  CwvAttributionSchema,
  CwvMetricIdSchema,
  CwvMetricSchema,
  CwvRatingSchema,
  CwvReportSchema,
  CwvRollupBucketSchema,
  IngestArtifactKindSchema,
  IngestArtifactMetaSchema,
  IngestArtifactSchema,
  IntelligenceConsistencyIssueSchema,
  IntelligenceConsistencySchema,
  IntelligenceReportSchema,
  JsonValueSchema,
  KnowledgeGraphStatsSchema,
  ParseDiagnosticDtoSchema,
  PersonaPresetsSchema,
  PrismCapabilitiesDtoSchema,
  PrismErrorSchema,
  RepoRelativePathSchema,
  StackPackageProfileSchema,
  StackProfileCoreSchema,
  StackProfileSchema,
  StackSignalSchema,
  UtilityJobKindSchema,
  UtilityJobProgressSchema,
  UtilityJobSchema,
  UtilityJobStatusSchema,
  UtilityMapLayerSchema,
  UtilityOverlayFindingSchema,
  UtilityOverlayKindInfoSchema,
  UtilityOverlayKindSchema,
  UtilityOverlayReportSchema,
  BackendAuthExposureSchema,
  BackendFrameworkSchema,
  BackendEndpointSchema,
  BackendDataLayerItemSchema,
  BackendEnvVarSchema,
  BackendIntegrationSchema,
  BackendBackgroundJobSchema,
  BackendReportSchema,
  EngineeringHealthMetricIdSchema,
  EngineeringHealthMetricSchema,
  EngineeringHotspotKindSchema,
  EngineeringHotspotSchema,
  EngineeringHealthReportSchema,
  CodeExplorerTargetSchema,
  CodeExplorerUsageSchema,
  CodeExplorerOwnerSchema,
  CodeExplorerOwnershipSchema,
  CodeExplorerRelatedItemSchema,
  CodeExplorerRelatedSchema,
  CodeExplorerSimilarItemSchema,
  CodeExplorerTimelineSchema,
  CodeExplorerReportSchema,
  parseDto,
  type BlastRadiusItem,
  type BlastRadiusReport,
  type BreakingChangeHint,
  type ChangeOrigin,
  type ImpactEditSite,
  type SafeDeleteReport,
  type RenameImpactReport,
  type TestImpactReport,
  type ConsentRecord,
  type CwvAttribution,
  type CwvMetric,
  type CwvMetricId,
  type CwvRating,
  type CwvReport,
  type CwvRollupBucket,
  type DnaReport,
  type FeatureInfo,
  type FileInventory,
  type FileInventoryEntry,
  type FileInventoryStatus,
  type GitActivity,
  type GitCommitRef,
  type GitContributor,
  type GitDayBucket,
  type GitFileSignal,
  type GitRecentFile,
  type GitRepoSummary,
  type GitSyncStatus,
  type GraphEdgeDto,
  type GraphLayout,
  type GraphLayoutPosition,
  type GraphNodeDto,
  type GraphSnapshotDto,
  type HealthScore,
  type Landmark,
  type MapBookmark,
  type BackendAuthExposure,
  type BackendFramework,
  type BackendEndpoint,
  type BackendDataLayerItem,
  type BackendEnvVar,
  type BackendIntegration,
  type BackendBackgroundJob,
  type BackendReport,
  type EngineeringHealthMetricId,
  type EngineeringHealthMetric,
  type EngineeringHotspotKind,
  type EngineeringHotspot,
  type EngineeringHealthReport,
  type CodeExplorerTarget,
  type CodeExplorerUsage,
  type CodeExplorerOwner,
  type CodeExplorerOwnership,
  type CodeExplorerRelatedItem,
  type CodeExplorerRelated,
  type CodeExplorerSimilarItem,
  type CodeExplorerTimeline,
  type CodeExplorerReport,
  type MapBookmarkStore,
  type MapCluster,
  type MapLayerDescriptor,
  type MapLayerId,
  type MapSearchHit,
  type MapZoomLevel,
  type NavigationRoute,
  type NavigationRouteResult,
  type RepositoryMap,
  type IndexCacheStats,
  type IndexProgressEvent,
  type IndexProgressPhase,
  type IndexSnapshot,
  type IndexSummary,
  type IndexedExport,
  type IndexedFile,
  type IndexedFileStatus,
  type IndexedImport,
  type IndexedReference,
  type IndexedSymbol,
  type IngestArtifact,
  type IngestArtifactKind,
  type IngestArtifactMeta,
  type IntelligenceConsistency,
  type IntelligenceConsistencyIssue,
  type IntelligenceReport,
  type JsonValue,
  type KnowledgeGraphStats,
  type ParseDiagnosticDto,
  type PersonaPresets,
  type PrismCapabilitiesDto,
  type PrismErrorDto,
  type StackPackageProfile,
  type StackProfile,
  type StackProfileCore,
  type StackSignal,
  type UtilityJob,
  type UtilityJobKind,
  type UtilityJobProgress,
  type UtilityJobStatus,
  type UtilityMapLayer,
  type UtilityOverlayFinding,
  type UtilityOverlayKind,
  type UtilityOverlayKindInfo,
  type UtilityOverlayReport,
} from "./schemas.js";

export {
  DeveloperPersona,
  StackDomain,
  type DeveloperPersonaId,
  type StackDomainId,
  type WellKnownDeveloperPersona,
  type WellKnownStackDomain,
} from "./stack.js";
