/**
 * Check that the documentation describes the Prism that exists (M-038 Phase 6).
 *
 * Prose is the one part of this repository the type checker cannot reach, so it
 * rots silently: a flag gets renamed, a Core method gets a better name, a
 * consent purpose is split in two, and the docs keep confidently describing the
 * old shape. Every claim checked here is one that was *wrong* in a first draft,
 * which is the argument for checking it mechanically rather than carefully.
 *
 *   bun run scripts/check-docs.mjs
 *
 * What it does not check: whether the prose is true in any deeper sense. It
 * checks that every name and flag the docs use is real.
 */

import { readdir, readFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const docsDir = join(repoRoot, "docs");

const problems = [];

function fail(file, message) {
  problems.push(`${relative(repoRoot, file)}: ${message}`);
}

async function loadBuilt(pkg) {
  const entry = join(repoRoot, "packages", pkg, "dist", "index.js");
  try {
    return await import(pathToFileURL(entry).href);
  } catch (cause) {
    throw new Error(
      `check-docs: cannot load @repo-prism/${pkg} from ${entry}. Run \`bun run build\` first.`,
      { cause },
    );
  }
}

async function markdownFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await markdownFiles(path)));
    else if (entry.name.endsWith(".md")) found.push(path);
  }
  return found.toSorted();
}

const { COMMANDS } = await loadBuilt("cli");
const { TOOL_NAMES } = await loadBuilt("mcp-server");
const { CONSENT_PURPOSE_IDS } = await loadBuilt("shared");

const commandsByName = new Map(COMMANDS.map((c) => [c.name, c]));
const toolNames = new Set(TOOL_NAMES);
const consentIds = new Set(CONSENT_PURPOSE_IDS);

/**
 * Global options accepted by every command, so a documented example that uses
 * one is not reporting an unknown flag for the subcommand.
 */
const GLOBAL_FLAGS = new Set([
  "-w",
  "--workspace",
  "--json",
  "--no-color",
  "-q",
  "--quiet",
  "--verbose",
  "-y",
  "--yes",
  "-V",
  "--version",
  "-h",
  "--help",
]);

/**
 * Snake_case tokens that legitimately appear in prose without being MCP tools.
 * Kept explicit so the check stays useful rather than being widened away.
 */
const NOT_TOOL_NAMES = new Set(["node_modules", "cache_db", "package_json"]);

const files = await markdownFiles(docsDir);

for (const file of files) {
  const text = await readFile(file, "utf8");
  const generated = text.startsWith("<!-- Generated by");

  // 1. Every `prism <command>` names a command that exists.
  for (const match of text.matchAll(/\bprism ([a-z][a-z-]*)/g)) {
    const name = match[1];
    if (!commandsByName.has(name)) {
      fail(file, `\`prism ${name}\` is not a command`);
    }
  }

  // 2. Every flag in a shell example is one that command accepts. Generated
  //    pages come from the table itself, so only hand-written prose can be
  //    wrong here.
  if (!generated) {
    // Shell blocks and inline spans both. The flag error this check exists to
    // catch was originally written inline, not in a block.
    const invocations = [
      ...[...text.matchAll(/```bash\n([\s\S]*?)```/g)].flatMap((block) =>
        block[1].split("\n"),
      ),
      ...[...text.matchAll(/`([^`\n]+)`/g)].map((span) => span[1]),
    ];

    for (const line of invocations) {
      const command =
        /^\s*(?:npx\s+@prism\/cli|prism)\s+([a-z][a-z-]*)(.*)$/.exec(line);
      if (!command) continue;

      const spec = commandsByName.get(command[1]);
      if (!spec) continue; // already reported above

      const accepted = new Set([
        ...GLOBAL_FLAGS,
        ...(spec.options ?? []).flatMap((option) =>
          option.flags.split(/[ ,]+/).filter((token) => token.startsWith("-")),
        ),
      ]);

      for (const flag of command[2].matchAll(/(?:^|\s)(--?[a-z][a-z-]*)/g)) {
        if (!accepted.has(flag[1])) {
          fail(file, `\`prism ${command[1]}\` does not accept \`${flag[1]}\``);
        }
      }
    }
  }

  // 3. Backticked snake_case tokens are MCP tool names, and must be real ones.
  for (const match of text.matchAll(/`([a-z]+(?:_[a-z]+)+)`/g)) {
    const token = match[1];
    if (!toolNames.has(token) && !NOT_TOOL_NAMES.has(token)) {
      fail(file, `\`${token}\` is not an MCP tool`);
    }
  }

  // 4. Backticked consent purposes must exist. Getting one of these wrong is
  //    the worst kind of documentation bug: it reads as a promise about what
  //    Prism will and will not do.
  for (const match of text.matchAll(/`((?:network|run)\.[a-z-]+)`/g)) {
    if (!consentIds.has(match[1])) {
      fail(file, `\`${match[1]}\` is not a consent purpose`);
    }
  }
}

// 5. Every consent purpose is documented somewhere. A capability that can reach
//    the network and is not written down is the gap that matters most.
const allText = (
  await Promise.all(files.map((file) => readFile(file, "utf8")))
).join("\n");

for (const id of consentIds) {
  if (!allText.includes(id)) {
    problems.push(`docs: consent purpose \`${id}\` is not documented anywhere`);
  }
}

// 6. Every workspace package is described. A package nobody wrote down is a
//    package a new contributor has to reverse-engineer.
const packagesPage = await readFile(
  join(docsDir, "architecture", "packages.md"),
  "utf8",
).catch(() => "");

for (const dir of ["packages", "apps"]) {
  const root = join(repoRoot, dir);
  for (const entry of await readdir(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const manifest = await readFile(
      join(root, entry.name, "package.json"),
      "utf8",
    ).catch(() => null);
    if (manifest === null) continue;

    const name = JSON.parse(manifest).name;
    if (!packagesPage.includes(`\`${name}\``)) {
      problems.push(
        `docs/architecture/packages.md: \`${name}\` is not described`,
      );
    }
  }
}

// 7. Every page is reachable from the sidebar. An unlinked page is a page that
//    only exists for whoever already knew the URL.
const config = await readFile(
  join(docsDir, ".vitepress", "config.ts"),
  "utf8",
).catch(() => "");

for (const file of files) {
  const route = `/${relative(docsDir, file).replace(/\.md$/, "")}`;
  if (route === "/index") continue;
  if (!config.includes(`"${route}"`)) {
    problems.push(`docs/.vitepress/config.ts: ${route} is not in the sidebar`);
  }
}

// 8. Every CLI command is reachable from the generated reference.
const reference = await readFile(
  join(docsDir, "reference", "cli-commands.md"),
  "utf8",
).catch(() => "");
for (const command of COMMANDS) {
  if (!reference.includes(`### \`prism ${command.name}`)) {
    problems.push(
      `docs/reference/cli-commands.md: \`prism ${command.name}\` is missing — run \`bun run docs:reference\``,
    );
  }
}

if (problems.length > 0) {
  console.error("check-docs: the docs describe a Prism that does not exist\n");
  for (const problem of problems) console.error(`  ${problem}`);
  console.error(`\ncheck-docs: ${problems.length} problem(s)`);
  process.exitCode = 1;
} else {
  console.log(`check-docs: ok (${files.length} pages)`);
}
